import Head from "next/head";
import { Main } from "src/components/Main/Main.jsx";

const Search = (props) => {
  return (
    <>
      <Head>
        <title>映画検索</title>
        <meta charset="utf-8" />
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          type="text/css"
          href="http://mplus-fonts.sourceforge.jp/webfonts/general-j/mplus_webfonts.css"
        ></link>
      </Head>
      <Main
        open={props.open}
        handleMenu={props.handleMenu}
        moviesData={props.searchedMovies}
        text={props.text}
        handleChange={props.handleChange}
        handleClickSearch={props.handleClickSearch}
        categories={props.categories}
      />
    </>
  );
};

export const getServerSideProps = async (context) => {
  const keyword = context.query.keyword;
  const src = `https://api.themoviedb.org/3/search/movie?api_key=54206ad48e363ded4ba03637e6c92d43&language=ja-JP&query=${keyword}&page=1&include_adult=false&region=JP`;
  try {
    const res = await fetch(src);
    if (!res.ok) {
      throw new Error("Failed to fetch movie data from API");
    }
    const movies = await res.json();
    const searchedMovies = movies.results || null;
    return {
      props: {
        searchedMovies,
      },
    };
  } catch (error) {
    console.error(error);
    return {
      props: {
        searchedMovies: null,
      },
    };
  }
};

export default Search;
