import Head from "next/head";
import { Inter } from "next/font/google";
import { Main } from "src/components/Main/Main.jsx";
const inter = Inter({ subsets: ["latin"] });

const Home = (props) => {
  return (
    <>
      <Head>
        <title>映画一覧 - AI映画レビュー</title>
        <meta charset="utf-8" />
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          type="text/css"
          href="http://mplus-fonts.sourceforge.jp/webfonts/general-j/mplus_webfonts.css"
        ></link>
      </Head>
      <Main open={props.open} handleMenu={props.handleMenu} />
    </>
  );
};

export default Home;
